const admin = {};
const user = {};

module.exports = {
  steps: {
    START_BOT: "START_BOT",
    ADAPTATION_CONTENT: "ADAPTATION_CONTENT",
    HOW_WE_WORK: "HOW_WE_WORK",
    ABOUT_THE_PLATFORM: "ABOUT_THE_PLATFORM",
    STAGES_OF_WORK: "STAGES_OF_WORK",
    DISTRIBUTION_OF_PROFILES: "DISTRIBUTION_OF_PROFILES",
    ABOUT_COMMUNICATION: "ABOUT_COMMUNICATION",
    EXTRA_INFO_ABOUT_PLATFORM: "EXTRA_INFO_ABOUT_PLATFORM",
    CONTRACT: "CONTRACT",
  },
  commands: {
    POST: "post",
  },
};
